[package]
name = "jmake"
version = "1.0.0"
edition = "2021"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true

[dependencies]
jni = { version = "0.21.1", features = ["invocation"] }
